.\" Manpage for jfetch. 
.TH man 9 "March 2021" "tuxfetch man page" "User Commands" 
.SH NAME 
tuxfetch \- A minimal Linux fetch script 
.SH SYNOPSIS 
jfetch 
.SH DESCRIPTION 
tuxfetch is a bash script which displays information about your system. 
.SH OPTIONS
tuxfetch can be customized by editing source
.SH "REPORTING BUGS" 
Report bugs to https://github.com/alonely0/jfetch/issues 
